spring.application.name=ToDoList
server.port=8082
spring.datasource.username=postgres
spring.datasource.password=xeon
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTc4MjUzMTEwNn0.8X2OqxKhjU5yFAkRC-DAFIM55OIO6hXLedXU_2N4PqE